instance_groups:
- name: opensearch_master
  vm_type: t3.xlarge
  jobs:
  - name: opensearch-platform
    properties:
      opensearch:
        delete_migrated_data: true

- name: maintenance
  vm_type: t3.large

- name: opensearch_dashboards
  vm_type: t3.xlarge
  jobs:
  - name: oauth2-proxy
    properties:
      redirect_url: https://logs-platform.fr.cloud.gov/oauth2/callback
      oidc_issuer_url: https://opslogin.fr.cloud.gov/oauth/token

- name: ingestor
  instances: 9
  vm_type: r5.xlarge.opensearch.ingestor
  jobs:
  - name: ingestor_syslog
    properties:
      logstash_ingestor:
        health:
          timeout: 900

- name: opensearch_data
  vm_type: r5.xlarge
  update:
    max_in_flight: 2
    canaries: 2
  jobs:
  - name: opensearch-platform
    properties:
      opensearch:
        delete_migrated_data: true

- name: smoke-tests
  vm_type: t3.medium
  jobs:
  - name: smoke_tests
    properties:
      smoke_tests:
        count_test:
          run: true
          minimum: 50000
          time_interval: "5m"
          time_field: "@timestamp"
          index_pattern: "logs-platform-*"

stemcells:
- alias: default
  os: ubuntu-jammy
  version: latest
